spring:
  #缓存配置
  redis:
    database: 0
    timeout: 6000ms
    password: TXwl@654321
    cluster:
      max-redirects: 3   #获取失败 最大重定向次数
      nodes:
        - 192.168.0.2:6379
        - 192.168.0.2:6382
        - 192.168.0.2:6380
        - 192.168.0.2:6383
        - 192.168.0.2:6381
        - 192.168.0.2:6384
    lettuce:
      pool:
        max-active: 1000  #连接池最大连接数(使用负值表示没有限制)
        max-idle: 10      #连接池中的最大空闲连接
        min-idle: 5       #连接池中的最小空闲连接
        max-wait: 3000      #连接池最大阻塞等待时间(使用负值表示没有限制)
  #数据源      
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.0.5:63100/txdata_db1?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true
      username: txwl_java
      password: DFvrvZpuCDWMLEXgyvDSK49vJCO1u2INSFdayenygQDQvb1zyXsPjPqAJcHjM4QcDiqvI2adJOlqensH4L7tvA==
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validationQuery: SELECT 'x'
      public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAI5cPP+Wtl1/Qd1Obl5suiP0ZYuA0EMHItXSOB9kJ0lRPhl6/t2ooCTsRxEP0pRaA+aF5idOF1SsqU0EifYHpzcCAwEAAQ==
      connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALQyScJPnDEtI+6TU82wl3srwfkXzy1+6X3CFcYMMd2Ha8u9ywPbs9hpT8XRjs8YtPRKdANNn+MGw/hzkXJh0G8CAwEAAQ==
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
            
##多数据源的配置
dynamic:
  datasource:
    ftpdata_master:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.0.5:63100/ftpdata_xmldb?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true
      username: txwl_dev
      password: ZAkA2Kw0X2AyuYKuDfBynhdqZTPaSA7jTyO0cX9z1xGsfIYhHi7g7NOobg0lJtiJG+DPLB5zXPFphNvkrlH06A==
      public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJkKQcktnmp6NKUsINaVkcRcQQY4ETwAFWuIoF3EEJAdGmzT586m+6i6iqzAZCvx8oo+Rq3vm0kO3KEXlZOBXRsCAwEAAQ==
      connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAL/Jm4M/5f+5zF4p8UnDZiuLZvlzMGSz5U9V+SbcK4jqewQoasAXOW3Xgy5psfhl+nHFc5m3AVYfhDhUw4ocUyECAwEAAQ==
