spring:
  #MQ配置
  #rabbitmq:
    #host: 192.168.0.88
    #port: 8889
    #username: admin
    #password: admin
    #virtual-host: /
    #publisher-confirms: true  #消息发送到交换机确认机制,是否确认回调
    #publisher-returns: true
  #缓存配置
  redis:
    database: 0
    #host: 127.0.0.1
    #port: 6379
    #sentinel:
      #master: mymaster
      #nodes: 192.168.0.223:27001
    #timeout: 6000ms
    password: Aa123456    
    cluster:
      max-redirects: 3   #获取失败 最大重定向次数
      nodes:
        - 192.168.0.52:6379
        - 192.168.0.52:6380
        - 192.168.0.53:6379
        - 192.168.0.53:6380
        - 192.168.0.54:6379
        - 192.168.0.54:6380
    lettuce:
      pool:
        max-active: 1000  #连接池最大连接数(使用负值表示没有限制)
        max-idle: 10      #连接池中的最大空闲连接
        min-idle: 5       #连接池中的最小空闲连接
        max-wait: 3000      #连接池最大阻塞等待时间(使用负值表示没有限制)
  #数据源      
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.0.8:3306/txdata_db1?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true
      username: root
      password: Apx2wPd1POgB0OSxAqvZDGtOzYar3AO3ui3jwnCtpbiaGOUGDQXnNdkR7K0P0h4Mx9X6j3cmLAqzI/DxsaNGOg==
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validationQuery: SELECT 'x'
      public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKFAQdoIdb6TZI8y+f0stJwocPDq7nwOgUWO11cJa1i+SQARnYpPSYt4M40IK3mGfWuamX+vysO5qP3bQ0DLPnMCAwEAAQ==
      connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKFAQdoIdb6TZI8y+f0stJwocPDq7nwOgUWO11cJa1i+SQARnYpPSYt4M40IK3mGfWuamX+vysO5qP3bQ0DLPnMCAwEAAQ==
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
            
##多数据源的配置
dynamic:
  datasource:
    ftpdata_master:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.0.8:3306/ftpdata_xmldb?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true
      username: root
      password: Apx2wPd1POgB0OSxAqvZDGtOzYar3AO3ui3jwnCtpbiaGOUGDQXnNdkR7K0P0h4Mx9X6j3cmLAqzI/DxsaNGOg==
      public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKFAQdoIdb6TZI8y+f0stJwocPDq7nwOgUWO11cJa1i+SQARnYpPSYt4M40IK3mGfWuamX+vysO5qP3bQ0DLPnMCAwEAAQ==
      connectionProperties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKFAQdoIdb6TZI8y+f0stJwocPDq7nwOgUWO11cJa1i+SQARnYpPSYt4M40IK3mGfWuamX+vysO5qP3bQ0DLPnMCAwEAAQ==

            